version: '3.8'
services:

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pg951357
      - POSTGRES_DB=notes
    container_name: notes-db
    networks:
    - notes_network
    # ports:
    #   - 5432:5432

  api:
    build: ./api
    container_name: notes-api
    environment:
      - DATABASE_URL=postgresql://postgres:pg951357@db:5432/notes
    ports:
      - 8080:8080
    networks:
    - notes_network
    depends_on:
    - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`fastapi.localhost`)"

  traefik:
    image: traefik:v2.6
    ports:
      - 8008:80
      - 8079:8080
    volumes:
      - "./traefik.dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  ui:
    build: ./ui
    container_name: notes-ui
    environment:
      - NEXT_PUBLIC_BASE_URL=http://notes-api:8080/
    ports:
      - 8081:3000
    networks:
    - notes_network
    depends_on:
    - api


volumes:
  postgres_data:

networks:
  notes_network:
    driver: bridge